apiVersion: v1
kind: Config
preferences: {}

current-context: whole-company-creds

contexts:
  - name: vault-company-name
    backend:
      - vault
  - name: whole-company-creds
    backend:
      - vault
      - gitlab

backends:
  - name: vault
    address: http://127.0.0.1:8200
    auth:
      env: VAULT_TOKEN
      # env: VAULT_DEV_ROOT_TOKEN_ID

  - name: gitlab
    address: https://gitlab.company.com
    auth:
      env: TOKEN_FOR_EXAMPLE
      exec:
        command: op
        args: ["read", "op://vault/prod-token/credential"]